services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jobber
      POSTGRES_PASSWORD: jobber
      POSTGRES_DB: jobber-auth
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
